import { ArrowSquareOut } from "@phosphor-icons/react/ArrowSquareOut";
import cliProof from "../../../docs/assets/walkthrough/cli-finding-and-replay.png";
import reportProof from "../../../docs/assets/walkthrough/compatibility-report.png";
import { SiteLink } from "./SiteLink";

const facts = [
  {
    label: "Finding",
    value: "Duplicate PSBT_GLOBAL_UNSIGNED_TX key accepted",
  },
  {
    label: "Boundary",
    value: "btcsuite PSBT 1.2.0 native parser",
  },
  {
    label: "Evidence",
    value: "Named finding, static report, and verified replay",
  },
] as const;

export function ProofWalkthrough() {
  return (
    <section className="proof-section" id="proof" aria-labelledby="proof-title">
      <div className="page-shell">
        <header className="proof-heading">
          <div>
            <span className="eyebrow">Evidence from a real v0.5.1 run</span>
            <h2 id="proof-title">From one command to a replayable finding.</h2>
          </div>
          <div>
            <p>
              A focused parser scenario completed safely, named the exact implementation boundary,
              and produced a self-contained report that can be verified again offline.
            </p>
            <SiteLink
              className="inline-link"
              href="/docs#walkthrough-catch-and-replay-a-real-finding"
            >
              Open the complete walkthrough <ArrowSquareOut aria-hidden="true" />
            </SiteLink>
          </div>
        </header>

        <div className="proof-media">
          <figure>
            <a href={cliProof} aria-label="Open full-size CLI proof">
              <img
                src={cliProof}
                alt="CLI finding and replay output"
                loading="lazy"
                decoding="async"
              />
            </a>
            <figcaption>
              <span>01</span>
              <strong>Run and replay</strong>
              <small>Actual v0.5.1 output, typeset with the local path shortened.</small>
            </figcaption>
          </figure>

          <figure>
            <a href={reportProof} aria-label="Open full-size generated report">
              <img
                src={reportProof}
                alt="Generated compatibility report"
                loading="lazy"
                decoding="async"
              />
            </a>
            <figcaption>
              <span>02</span>
              <strong>Inspect the evidence</strong>
              <small>Direct capture of the static HTML artifact generated by the same run.</small>
            </figcaption>
          </figure>
        </div>

        <dl className="proof-facts">
          {facts.map((fact) => (
            <div key={fact.label}>
              <dt>{fact.label}</dt>
              <dd>{fact.value}</dd>
            </div>
          ))}
        </dl>
      </div>
    </section>
  );
}
